packages:
  - "apps/*"
  - "packages/*"
  - "packages/integrations/*"
  - "packages/integrations/whatsapp/*"
  - "packages/integrations/pep/*"
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
